config/routes.rb
Leasify::Application.routes.draw do

  require 'subdomain'

  resources :pages do
    collection do
      post "sort"
    end
  end

  resources :availabilities do
    collection do
      post "sort"
    end
  end

  resources :contacts do
    collection do
      post "sort"
    end
  end

  scope :dashboard do
    resources :pages, :availabilities, :contacts, :property_informations, :theme_options, :sites, :users, :homepage_galleries, :wizards
    get '/', to: 'dashboards#index', as: :dashboard
    get '/property',         to:'property_informations#index', as: :property
    get '/property/address', to:'property_informations#address', as: :address
    get '/property/amenities', to:'property_informations#amenities', as: :amenities_property
    get '/theme-options/logo', to:'theme_options#index', as: :logo
    get '/theme-options/homepage/content', to:'theme_options#homepage_content', as: :homepage_content
    get '/theme-options/homepage/gallery', to:'theme_options#homepage_gallery', as: :homepage_image_gallery
    get '/templates', to:'theme_options#template', as: :template
    get '/theme-options/settings', to:'theme_options#theme_settings', as: :theme_settings
    get '/tour', to:'dashboards#tour', as: :tour
    get '/redirect', to:'sites#redirect', as: :redirect

    # Wizard routes
    get '/wizard/templates', to: 'wizards#templates', as: :wizard_templates
    get '/wizard/customize', to: 'wizards#customize', as: :wizard_customize
    get '/wizard/homepage', to: 'wizards#homepage_content', as: :wizard_homepage_content
    get '/wizard/property', to: 'wizards#property_information', as: :wizard_property_information
    get '/wizard/property/address', to: 'wizards#property_address', as: :wizard_property_address
    get '/wizard/property/amenities', to: 'wizards#property_amenities', as: :wizard_property_amenities
    get '/wizard/homepage/gallery', to: 'wizards#homepage_gallery', as: :wizard_homepage_gallery
    get '/wizard/page/new', to: 'wizards#new_page', as: :wizard_new_page
    get '/wizard/almost/finished', to: 'wizards#almost_finished', as: :wizard_almost_finished
  end



  scope :admin do
    resources :theme_names, :sidebar_links, :admin, :amenities
    get '/themes', to: 'theme_names#index', as: :admin_theme
    get '/themes/new', to: 'theme_names#new', as: :admin_theme_new
    get '/themes/:id/edit', to: 'theme_names#edit', as: :admin_theme_edit
    get '/themes/:id/', to: 'theme_names#show', as: :admin_theme_show

    get '/sidebar/nav', to: 'sidebar_links#index', as: :admin_sidebar
    get '/sidebar/nav/new', to: 'sidebar_links#new', as: :admin_sidebar_new
    get '/sidebar/nav/:id/edit', to: 'sidebar_links#edit', as: :admin_sidebar_edit
    get '/sidebar/nav/:id', to: 'sidebar_links#show', as: :admin_sidebar_show

    get '/users', to: 'admin#users_list', as: :users_list

    get '/amenities', to: 'amenities#index', as: :admin_amenities
    get '/amenities/new', to: 'amenities#new', as: :admin_amenities_new
    get '/amenities/:id/edit', to: 'amenities#edit', as: :admin_amenities_edit
    get '/amenities/:id', to: 'amenities#show', as: :admin_amenities_show

    get '/slider', to: 'admin#slider_test'
  end

  constraints(Subdomains) do
    get '/' => 'static_pages#home'
  end

  root to: "static_pages#home"
  get '/help', to: 'static_pages#help', as: :help
  get '/templates', to: 'static_pages#templates', as: :templates
  get '/beta/signup', to: 'static_pages#beta_signup', as: :beta_signup_mailchimp
  get '/beta/confirmation', to: 'static_pages#beta_confirmation', as: :beta_confirmation_mailchimp
  get '/leasing', to: 'static_pages#leasing', as: :leasing
  get '/leasing/:id', to: 'availabilities#show', as: :leasing_show

  get "sunnyside/index"
  get "avaya/index"










  resources :users, :only => :show

  devise_for :users, :controllers => { :registrations => "registrations" },
             :skip => [:sessions, :passwords]

  devise_scope :user do
    get  '/register', to: 'devise/registrations#new', as: :register
    # post '/register', to: 'devise/registrations#create', as: :user_registration
    # put  '/register', to: 'devise/registrations#edit', as: :registration
    get  '/dashboard/profile/edit', to: 'devise/registrations#edit', as: :edit

    get  '/login', to: 'devise/sessions#new', as: :new_user_session
    post '/login', to: 'devise/sessions#create', as: :user_session
    get  '/logout', to: 'devise/sessions#destroy', as: :logout

    get  '/password/new', to: 'devise/passwords#new', as: :new_user_password
    post '/password/new', to: 'devise/passwords#create', as: :user_password
  end

  get '/:id', to: 'pages#show', as: 'pages_id'

  #post '/email_processor' => 'griddler/emails#create'

end

app/models/sidebar_link.rb
class SidebarLink < ActiveRecord::Base
end

app/controllers/sidebar_links_controller.rb
class SidebarLinksController < ApplicationController
  before_action :set_sidebar_link, only: [:show, :edit, :update, :destroy]
  before_action :authenticate_user!
  before_action :admin_role

  def index
    @sidebar_links = SidebarLink.all
  end

  def show
  end

  def new
    @sidebar_link = SidebarLink.new
    @title = "New Sidebar Link"
  end

  # GET /sidebar_links/1/edit
  def edit
    @title = @sidebar_link.name
  end

  def create
    @sidebar_link = SidebarLink.new(sidebar_link_params)

    respond_to do |format|
      if @sidebar_link.save
        format.html { redirect_to @sidebar_link, notice: 'Sidebar link was successfully created.' }
        format.json { render action: 'show', status: :created, location: @sidebar_link }
      else
        format.html { render action: 'new' }
        format.json { render json: @sidebar_link.errors, status: :unprocessable_entity }
      end
    end
  end

  def update
    respond_to do |format|
      if @sidebar_link.update(sidebar_link_params)
        format.html { redirect_to @sidebar_link, notice: 'Sidebar link was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: 'edit' }
        format.json { render json: @sidebar_link.errors, status: :unprocessable_entity }
      end
    end
  end

  def destroy
    @sidebar_link.destroy
    respond_to do |format|
      format.html { redirect_to sidebar_links_url }
      format.json { head :no_content }
    end
  end

  private

  def set_sidebar_link
    @sidebar_link = SidebarLink.find(params[:id])
  end

  def sidebar_link_params
    params.require(:sidebar_link).permit(:name, :link_to, :icon)
  end

  def admin_role
    redirect_to dashboard_path unless current_user.admin?
  end
end

app/helpers/sidebar_links_helper.rb
module SidebarLinksHelper
end

app/views/sidebar_links/_form.html.haml
= form_for(@sidebar_link) do |f|
  - if @sidebar_link.errors.any?
    #error_explanation
      %h2
        = pluralize(@sidebar_link.errors.count, "error")
        prohibited this sidebar_link from being saved:
      %ul
        - @sidebar_link.errors.full_messages.each do |msg|
          %li= msg
  %section.scrollable.wrapper.w-f
    .panel-body
      .add-page
        %h3= @title
        .row
          .col-md-8
            .form-group
              = f.label :name
              = f.text_field :name, class: "form-control"
            .form-group
              = f.label :link_to
              = f.text_field :link_to, class: "form-control"
            .form-group
              = f.label :icon
              = f.text_field :icon, class: "form-control"
  %footer.footer.bg-white.b-t
    .row.text-center-xs
      .col-md-6.hidden-sm
      .col-md-6.col-sm-12.text-right.text-center-xs
        = f.submit "Save", class: "btn btn-success btn-more-padding"

app/views/sidebar_links/edit.html.haml
= render 'form'

app/views/sidebar_links/index.html.haml
- unless @sidebar_links.empty?
  %header.header.bg-white.b-b.clearfix
    .row.m-t-sm
      .col-sm-8.m-b-xs
        .btn-group
          %button.btn.btn-sm.btn-default{:title => "Refresh", :type => "button"}
            %i.fa.fa-refresh
          %button.btn.btn-sm.btn-default{:title => "Remove", :type => "button"}
            %i.fa.fa-trash-o
          %button.btn.btn-sm.btn-default{"data-toggle" => "dropdown", :title => "Filter", :type => "button"}
            %i.fa.fa-filter
            %span.caret
          %ul.dropdown-menu
            %li
              %a{:href => "#"} Action
            %li
              %a{:href => "#"} Another action
            %li
              %a{:href => "#"} Something else here
            %li.divider
            %li
              %a{:href => "#"} Separated link
        = link_to admin_sidebar_new_path, class: "btn btn-sm btn-default" do
          %i.fa.fa-plus
          New Sidebar Link
      .col-sm-4.m-b-xs
        .input-group
          %input.input-sm.form-control.input-header{:placeholder => "Search", :type => "text"}/
          %span.input-group-btn
            %button.btn.btn-sm.btn-default{:type => "button"} Go!
%section.scrollable.wrapper.w-f
  - if @sidebar_links.empty?
    .center
      %h1 You don't have any sidebar links created!
      %p.m-b-md Create sidebar links to include in your website.
      = link_to 'New theme', admin_theme_new_path, class: "btn btn-success"
  - else
    %h3.m-t-none.m-b-md Themes
    %section.panel.panel-default
      .table-responsive
        %table.table.table-striped.m-b-none.sidebar_links
          %thead
            %tr
              %th{:width => "20"}
                %label.checkbox.m-n.i-checks
                  %input{:type => "checkbox"}/
                  %i
              %th.name{"data-toggle" => "class"} Menu Name
              %th.date Date Created
              %th{:width => "30"}
          %tbody
            - @sidebar_links.each do |sidebar|
              %tr.table-edit
                %td
                  %label.checkbox.m-n.i-checks
                    %input{:name => "ids[]", :type => "checkbox"}/
                    %i
                %td
                  = link_to sidebar.name, "#", class: "pull-left m-r-sm"
                  %ul.edit-links
                    %li
                      = link_to "Edit", admin_sidebar_edit_path(sidebar)
                      |
                    %li= link_to "View", admin_sidebar_show_path(sidebar)
                %td= sidebar.created_at.strftime("%B %e, %Y")
                %td
                  %a{"data-target" => "#sidebar#{sidebar.id}", "data-toggle" => "modal", :href => ""}
                    %i.fa.fa-trash-o
              / Modal
              .modal.fade{"aria-hidden" => "true", "aria-labelledby" => "myModalLabel", :id => "sidebar#{sidebar.id}", :role => "dialog", :tabindex => "-1"}
                .modal-dialog
                  .modal-content
                    .modal-header
                      %button.close{"aria-hidden" => "true", "data-dismiss" => "modal", :type => "button"} ×
                      %h4#myModalLabel.modal-title Are you sure?
                    .modal-body
                      Once the sidebar is deleted, it's gone forever!
                    .modal-footer
                      %button.btn.btn-link{"data-dismiss" => "modal", :type => "button"} Close
                      = link_to "Delete", sidebar, method: :delete, class: "btn btn-danger"

app/views/sidebar_links/new.html.haml
= render 'form'

app/views/sidebar_links/show.html.haml
%p#notice= notice
%p
  %strong Name:
  = @sidebar_link.name
%p
  %strong Link to:
  = @sidebar_link.link_to
%p
  %strong Icon:
  = @sidebar_link.icon
= link_to 'Edit', admin_sidebar_edit_path(@sidebar_link)
|