config/routes.rb
Leasify::Application.routes.draw do

  require 'subdomain'

  resources :pages do
    collection do
      post "sort"
    end
  end

  resources :availabilities do
    collection do
      post "sort"
    end
  end

  resources :contacts do
    collection do
      post "sort"
    end
  end

  scope :dashboard do
    resources :pages, :availabilities, :contacts, :property_informations, :theme_options, :sites, :users, :homepage_galleries, :wizards
    get '/', to: 'dashboards#index', as: :dashboard
    get '/property',         to:'property_informations#index', as: :property
    get '/property/address', to:'property_informations#address', as: :address
    get '/property/amenities', to:'property_informations#amenities', as: :amenities_property
    get '/theme-options/logo', to:'theme_options#index', as: :logo
    get '/theme-options/homepage/content', to:'theme_options#homepage_content', as: :homepage_content
    get '/theme-options/homepage/gallery', to:'theme_options#homepage_gallery', as: :homepage_image_gallery
    get '/templates', to:'theme_options#template', as: :template
    get '/theme-options/settings', to:'theme_options#theme_settings', as: :theme_settings
    get '/tour', to:'dashboards#tour', as: :tour
    get '/redirect', to:'sites#redirect', as: :redirect

    # Wizard routes
    get '/wizard/templates', to: 'wizards#templates', as: :wizard_templates
    get '/wizard/customize', to: 'wizards#customize', as: :wizard_customize
    get '/wizard/homepage', to: 'wizards#homepage_content', as: :wizard_homepage_content
    get '/wizard/property', to: 'wizards#property_information', as: :wizard_property_information
    get '/wizard/property/address', to: 'wizards#property_address', as: :wizard_property_address
    get '/wizard/property/amenities', to: 'wizards#property_amenities', as: :wizard_property_amenities
    get '/wizard/homepage/gallery', to: 'wizards#homepage_gallery', as: :wizard_homepage_gallery
    get '/wizard/page/new', to: 'wizards#new_page', as: :wizard_new_page
    get '/wizard/almost/finished', to: 'wizards#almost_finished', as: :wizard_almost_finished
  end



  scope :admin do
    resources :theme_names, :sidebar_links, :admin, :amenities
    get '/themes', to: 'theme_names#index', as: :admin_theme
    get '/themes/new', to: 'theme_names#new', as: :admin_theme_new
    get '/themes/:id/edit', to: 'theme_names#edit', as: :admin_theme_edit
    get '/themes/:id/', to: 'theme_names#show', as: :admin_theme_show

    get '/sidebar/nav', to: 'sidebar_links#index', as: :admin_sidebar
    get '/sidebar/nav/new', to: 'sidebar_links#new', as: :admin_sidebar_new
    get '/sidebar/nav/:id/edit', to: 'sidebar_links#edit', as: :admin_sidebar_edit
    get '/sidebar/nav/:id', to: 'sidebar_links#show', as: :admin_sidebar_show

    get '/users', to: 'admin#users_list', as: :users_list

    get '/amenities', to: 'amenities#index', as: :admin_amenities
    get '/amenities/new', to: 'amenities#new', as: :admin_amenities_new
    get '/amenities/:id/edit', to: 'amenities#edit', as: :admin_amenities_edit
    get '/amenities/:id', to: 'amenities#show', as: :admin_amenities_show

    get '/slider', to: 'admin#slider_test'
  end

  constraints(Subdomains) do
    get '/' => 'static_pages#home'
  end

  root to: "static_pages#home"
  get '/help', to: 'static_pages#help', as: :help
  get '/templates', to: 'static_pages#templates', as: :templates
  get '/beta/signup', to: 'static_pages#beta_signup', as: :beta_signup_mailchimp
  get '/beta/confirmation', to: 'static_pages#beta_confirmation', as: :beta_confirmation_mailchimp
  get '/leasing', to: 'static_pages#leasing', as: :leasing
  get '/leasing/:id', to: 'availabilities#show', as: :leasing_show

  get "sunnyside/index"
  get "avaya/index"










  resources :users, :only => :show

  devise_for :users, :controllers => { :registrations => "registrations" },
             :skip => [:sessions, :passwords]

  devise_scope :user do
    get  '/register', to: 'devise/registrations#new', as: :register
    # post '/register', to: 'devise/registrations#create', as: :user_registration
    # put  '/register', to: 'devise/registrations#edit', as: :registration
    get  '/dashboard/profile/edit', to: 'devise/registrations#edit', as: :edit

    get  '/login', to: 'devise/sessions#new', as: :new_user_session
    post '/login', to: 'devise/sessions#create', as: :user_session
    get  '/logout', to: 'devise/sessions#destroy', as: :logout

    get  '/password/new', to: 'devise/passwords#new', as: :new_user_password
    post '/password/new', to: 'devise/passwords#create', as: :user_password
  end

  get '/:id', to: 'pages#show', as: 'pages_id'

  #post '/email_processor' => 'griddler/emails#create'

end

app/controllers/wizards_controller.rb
class WizardsController < ApplicationController
	before_action :authenticate_user!
	before_action :set_subdomain
	before_action :set_wizard
	before_action :set_subdomain
	before_action :redirect_if_www

	def templates
		
	end

	def customize
		
	end

	def homepage_content
		
	end

	def property_information
		@propertyinformations = PropertyInformation.where(site_id: @site.id).first
  end

	def property_address
		@propertyinformations = PropertyInformation.where(site_id: @site.id).first
	end

	def property_amenities
		@propertyinformations = PropertyInformation.where(site_id: @site.id).first
		@amenities_common = Amenity.where(category: "Common")
    @amenities_extra = Amenity.where(category: "Extra")
	end

	def homepage_gallery
		@homepage_gallery    = HomepageGallery.where(site_id: @site.id).first
    @homepage_galleries  = HomepageGallery.where(site_id: @site.id).all
    @themeoptions.homepage_galleries.build
	end

	def new_page
		@page = Page.new
	end

	def almost_finished

	end

	


	private

		def set_wizard
			if request.subdomain.present? && request.subdomain != "www"
				@themeoptions = ThemeOption.where(user_id: current_user.id).first && ThemeOption.where(site_id: @site.id).first
				@templates = ThemeName.where(published: true).all
			end
		end

		def set_subdomain
			if request.subdomain.present? && request.subdomain != "www"
				@subdomain           = request.subdomain
				@site                = Site.where(subdomain: request.subdomain).first
				@user                = User.where(id: @site.user_id).first
				@pages               = Page.where(site_id: @site.id).all
				@availabilities      = Availability.where(site_id: @site.id).all
				@propertyinformation = PropertyInformation.where(site_id: @site.id).first
				@contacts            = Contact.where(site_id: @site.id).all
			end
		end

		def redirect_if_www
      if !request.subdomain.present? || request.subdomain == "www"
        redirect_to dashboard_path
      end
    end

end

app/helpers/wizards_helper.rb
module WizardsHelper

	def state_select_wizard
		@subdomain = request.subdomain
    @site      = Site.where(subdomain: request.subdomain).first
    @property_informations = PropertyInformation.where(site_id: @site.id).first
		if (params[:controller] == "wizards") && !@property_informations.state.nil?
	    return @property_informations.state
	  else
	  	return "Select State"
	  end
	end

	def active_class(path)
		'class=active' if current_page?(path)
	end

	def active_class_wo_class(path)
		'active' if current_page?(path)
	end

end

app/views/wizards/_body_size.html.haml
%li
  %a.proximanova{:href => "#"}
    = f.radio_button :body_size, 10
    = "10px"
%li
  %a.proximanova{:href => "#"}
    = f.radio_button :body_size, 11
    = "11px"
%li
  %a.proximanova{:href => "#"}
    = f.radio_button :body_size, 12
    = "12px"
%li
  %a.proximanova{:href => "#"}
    = f.radio_button :body_size, 14
    = "14px"
%li
  %a.proximanova{:href => "#"}
    = f.radio_button :body_size, 16
    = "16px"
%li
  %a.proximanova{:href => "#"}
    = f.radio_button :body_size, 18
    = "18px"
%li
  %a.proximanova{:href => "#"}
    = f.radio_button :body_size, 20
    = "20px"
%li
  %a.proximanova{:href => "#"}
    = f.radio_button :body_size, 22
    = "22px"
%li
  %a.proximanova{:href => "#"}
    = f.radio_button :body_size, 24
    = "24px"
%li
  %a.proximanova{:href => "#"}
    = f.radio_button :body_size, 26
    = "26px"
%li
  %a.proximanova{:href => "#"}
    = f.radio_button :body_size, 28
    = "28px"
%li
  %a.proximanova{:href => "#"}
    = f.radio_button :body_size, 30
    = "30px"
%li
  %a.proximanova{:href => "#"}
    = f.radio_button :body_size, 36
    = "36px"
%li
  %a.proximanova{:href => "#"}
    = f.radio_button :body_size, 48
    = "48px"
%li
  %a.proximanova{:href => "#"}
    = f.radio_button :body_size, 60
    = "60px"
%li
  %a.proximanova{:href => "#"}
    = f.radio_button :body_size, 72
    = "72px"

app/views/wizards/_font_color.html.haml
/ start color panel
.panel
  %a.accordion-toggle{"data-parent" => "#accordion", "data-toggle" => "collapse", :href => "#color"}
    Color
    %i.i.i-arrow-down5.pull-right
  #color.panel-collapse.collapse{:style => "height: auto;"}
    #mainheading_color.form-group
      = f.label :mainheading_color, "Site Title"
      .input-group.demo2.colorpicker-component
        %span.input-group-addon.border-all
          %i
        = f.text_field :mainheading_color, class: "form-control no-bg", value: @themeoptions.mainheading_color
    / end form group mainheading color
    #subheading_color.form-group
      = f.label :subheading_color, "Sub Title"
      .input-group.demo2.colorpicker-component
        %span.input-group-addon.border-all
          %i
        = f.text_field :subheading_color, class: "form-control no-bg", value: @themeoptions.subheading_color
    / end form group subheading color
    #page_title_color.form-group
      = f.label :page_title_color, "Page Titles"
      .input-group.demo2.colorpicker-component
        %span.input-group-addon.border-all
          %i
        = f.text_field :page_title_color, class: "form-control no-bg", value: @themeoptions.page_title_color
    / end form group page titles color
    #page_subtitle_color.form-group
      = f.label :page_subtitle_color, "Page Sub Titles"
      .input-group.demo2.colorpicker-component
        %span.input-group-addon.border-all
          %i
        = f.text_field :page_subtitle_color, class: "form-control no-bg", value: @themeoptions.page_subtitle_color
    / end form group page sub titles color
    #body_color.form-group
      = f.label :body_color, "Body Color"
      .input-group.demo2.colorpicker-component
        %span.input-group-addon.border-all
          %i
        = f.text_field :body_color, class: "form-control no-bg", value: @themeoptions.body_color
    / end form group body color
    #body_heading_color.form-group
      = f.label :body_heading_color, "Body Heading Color"
      .input-group.demo2.colorpicker-component
        %span.input-group-addon.border-all
          %i
        = f.text_field :body_heading_color, class: "form-control no-bg", value: @themeoptions.body_heading_color
    / end form group body heading color
    #nav_color.form-group
      = f.label :nav_color, "Navigation Color"
      .input-group.demo2.colorpicker-component
        %span.input-group-addon.border-all
          %i
        = f.text_field :nav_color, class: "form-control no-bg", value: @themeoptions.nav_color
    / end form group body heading color
    #navhover_color.form-group
      = f.label :navhover_color, "Navigation Hover Color"
      .input-group.demo2.colorpicker-component
        %span.input-group-addon.border-all
          %i
        = f.text_field :navhover_color, class: "form-control no-bg", value: @themeoptions.navhover_color
    / end form group body heading color
    #footer_color.form-group
      = f.label :footer_color, "Footer Color"
      .input-group.demo2.colorpicker-component
        %span.input-group-addon.border-all
          %i
        = f.text_field :footer_color, class: "form-control no-bg", value: @themeoptions.footer_color
    / end form group body heading color
    #link_color.form-group
      = f.label :link_color, "Link Color"
      .input-group.demo2.colorpicker-component
        %span.input-group-addon.border-all
          %i
        = f.text_field :link_color, class: "form-control no-bg", value: @themeoptions.link_color
    / end form group body heading color
  / end id color
/ end color panel

app/views/wizards/_footer_size.html.haml
%li
  %a.proximanova{:href => "#"}
    = f.radio_button :footer_size, 10
    = "10px"
%li
  %a.proximanova{:href => "#"}
    = f.radio_button :footer_size, 11
    = "11px"
%li
  %a.proximanova{:href => "#"}
    = f.radio_button :footer_size, 12
    = "12px"
%li
  %a.proximanova{:href => "#"}
    = f.radio_button :footer_size, 14
    = "14px"
%li
  %a.proximanova{:href => "#"}
    = f.radio_button :footer_size, 16
    = "16px"
%li
  %a.proximanova{:href => "#"}
    = f.radio_button :footer_size, 18
    = "18px"
%li
  %a.proximanova{:href => "#"}
    = f.radio_button :footer_size, 20
    = "20px"
%li
  %a.proximanova{:href => "#"}
    = f.radio_button :footer_size, 22
    = "22px"
%li
  %a.proximanova{:href => "#"}
    = f.radio_button :footer_size, 24
    = "24px"
%li
  %a.proximanova{:href => "#"}
    = f.radio_button :footer_size, 26
    = "26px"
%li
  %a.proximanova{:href => "#"}
    = f.radio_button :footer_size, 28
    = "28px"
%li
  %a.proximanova{:href => "#"}
    = f.radio_button :footer_size, 30
    = "30px"
%li
  %a.proximanova{:href => "#"}
    = f.radio_button :footer_size, 36
    = "36px"
%li
  %a.proximanova{:href => "#"}
    = f.radio_button :footer_size, 48
    = "48px"
%li
  %a.proximanova{:href => "#"}
    = f.radio_button :footer_size, 60
    = "60px"
%li
  %a.proximanova{:href => "#"}
    = f.radio_button :footer_size, 72
    = "72px"

app/views/wizards/_heading_text_transform.html.haml
%li
  %a{:href => "#"}
    = f.radio_button :heading_text_transform, "capitalize"
    = "Capitalize"
%li
  %a{:href => "#"}
    = f.radio_button :heading_text_transform, "uppercase"
    = "Uppercase"
%li
  %a{:href => "#"}
    = f.radio_button :heading_text_transform, "lowercase"
    = "Lowercase"
%li
  %a{:href => "#"}
    = f.radio_button :heading_text_transform, "none"
    = "None"

app/views/wizards/almost_finished.html.haml
%body
  %section
    %section.hbox.stretch.wizard
      %aside
        %section.vbox
          %header.header.bg-white.b-b.clearfix
            .row
              .col-sm-4
                = link_to wizard_homepage_gallery_path, class: "btn btn-default" do
                  Back
              .col-sm-4
                50% complete
                .progress.progress-xs{:style => "margin:0"}
                  .progress-bar.bg-info{"data-original-title" => "50%", "data-toggle" => "tooltip", :style => "width: 50%"}
              .col-sm-4.text-right
                = link_to dashboard_path, class: "btn btn-danger" do
                  %span{:style => "font-weight:700;"} Exit Wizard
          %section.scrollable.wrapper.finished
            .panel-body
              .add-page
                .row
                  .col-md-8.col-md-offset-2
                    .top-info.center
                      %h1 Almost finished!
                      .row
                        .col-lg-8.col-lg-offset-2
                          %p.m-t-lg
                            Now we need to add pages, availabilities, and contacts to your website. But, we're going to have to
                            exit the wizard in order to complete these final steps. Your dashboard will have the appropriate links to
                            complete these tasks. But, here are a few steps to help you get started.
                    %section.steps
                      %h2 Step 1: Add Pages
                      %p
                        You can add and manage your pages in the "Pages" section of your dashboard. You can upload an optional image for each of
                        your pages. Pages only accept one image per page. #{link_to "Add new page", new_page_path}
                      = image_tag('/assets/addpage.jpg', class: "img-responsive img-thumbnail")
                    %section.steps
                      %h2 Step 2: Add Availabilities
                      %p
                        You can add and manage your availability listings in the "Availabilities" section of your dashboard. Unlike pages, you may upload mulitple images to showcase your space. #{link_to "Add new listing", new_availability_path}
                      = image_tag('/assets/addlisting.jpg', class: "img-responsive img-thumbnail")
                    %section.steps
                      %h2 Step 3: Add Contacts
                      %p
                        You can add your colleages contacts that are associated with this property. #{link_to "Add new contacts", new_contact_path}
                      = image_tag('/assets/contacts.jpg', class: "img-responsive img-thumbnail")

app/views/wizards/customize.html.haml
%body
  %section.wizard
    = form_for(@themeoptions, html: { class: "customize-wizard" }) do |f|
      %header.header.bg-white.b-b.clearfix
        .row
          .col-sm-4
            = link_to wizard_templates_path, class: "btn btn-default" do
              Back
          .col-sm-4
            - if Rails.env.development?
              50% complete
              .progress.progress-xs{:style => "margin:0"}
                .progress-bar.bg-info{"data-original-title" => "50%", "data-toggle" => "tooltip", :style => "width: 50%"}
          .col-sm-4.text-right
            = f.submit "Save Changes", class: "btn btn-success"
            = link_to wizard_homepage_content_path, class: "btn btn-default" do
              Continue
      %section.hbox.stretch
        %aside
          %section.vbox
            %div{:style => "position:absolute; height:100%; width:100%;"}
              - if Rails.env.production?
                %iframe{:src => "http://#{request.subdomain}.leasify.co"}
              - elsif Rails.env.development?
                %iframe{:src => "http://#{request.subdomain}.lvh.me:3000"}
        %aside#wizard_right_aside.wrapper.b-l.aside-md
          %section.vbox
            %section.scrollable
              %h4 Customize Design
              #accordion.accordian
                = render 'logo', :f => f
                = render 'typography', :f => f
                = render 'font_size_panel', :f => f
                = render 'font_color', :f => f
              / end accordian
  #customize_tooltip.fake_tooltip.customize_tooltip
    %span.arrow.right
    Let's customize your site!
    %br/
    You can change your websites fonts, font size, colors, and upload a logo.
  = javascript_tag do
    = render "customize.js"

app/views/wizards/homepage_gallery.html.haml
%body
  %section.wizard
    = form_for(@themeoptions, html: { class: "customize-wizard", multipart: true }) do |f|
      %header.header.bg-white.b-b.clearfix
        .row
          .col-sm-4
            = link_to wizard_homepage_content_path, class: "btn btn-default" do
              Back
          .col-sm-4
            - if Rails.env.development?
              50% complete
              .progress.progress-xs{:style => "margin:0"}
                .progress-bar.bg-info{"data-original-title" => "50%", "data-toggle" => "tooltip", :style => "width: 50%"}
          .col-sm-4.text-right
            = f.submit "Save Changes", class: "btn btn-success"
            = link_to wizard_almost_finished_path, class: "btn btn-default" do
              Continue
      %section.hbox.stretch
        %aside
          %section.vbox
            %div{:style => "position:absolute; height:100%; width:100%;"}
              - if Rails.env.production?
                %iframe{:src => "http://#{request.subdomain}.leasify.co"}
              - elsif Rails.env.development?
                %iframe{:src => "http://#{request.subdomain}.lvh.me:3000"}
        %aside#wizard_right_aside.wrapper.b-l.aside-md
          %section.vbox
            %section.scrollable
              = f.fields_for :homepage_galleries do |builder|
                - if builder.object.new_record?
                  = builder.hidden_field :site_id, value: @site.id
                  = builder.hidden_field :user_id, value: current_user.id
                  = builder.file_field :homepage_gallery_image, as: :file, class: "filestyle", id: "lefile2", style: "position: fixed; left: -500px;"
                  .bootstrap-filestyle{:style => "display: inline;"}
                    %label.btn.btn-info.btn-block.m-b-lg{:for => "lefile2"}
                      %i.i.i-images
                      %span{:style => "font-weight:700;"} Upload Image
                  %p Let's upload and preview an image for your homepage. Don't forget to Save!
                  %p You can view and manage the images in your homepage gallery in the "Theme Options" in your main dashboard.
  #homepage_gallery.fake_tooltip.homepage_gallery
    %span.arrow.right
    %p Upload and preview a background image for your homepage.
  :javascript
    // Image preview before upload
    var preview2 = $('iframe').contents().find('.wizard');

        $("#lefile2").change(function(event){
             var input = $(event.currentTarget);
             var file = input[0].files[0];
             var reader = new FileReader();
             $('iframe').contents().find('.wizard').removeAttr("style");
             reader.onload = function(e){
                 image_base64 = e.target.result;
                 $('iframe').contents().find('.wizard').attr("style", "background-image:url(" + image_base64 + ")");
                 $('iframe').contents().find('.wizard img').attr('src', image_base64);
             };
             reader.readAsDataURL(file);
             


        });

app/views/wizards/new_page.html.haml
%body
  %section
    = form_for(@page, html: { class: "propertyinformations-wizard" }) do |f|
      %section.hbox.stretch.wizard
        %aside
          %section.vbox
            %header.header.bg-white.b-b.clearfix
              .row
                .col-sm-4.col-sm-offset-4.m-b-xs
                  50% complete
                  .progress.progress-xs{:style => "margin:0"}
                    .progress-bar.bg-info{"data-original-title" => "50%", "data-toggle" => "tooltip", :style => "width: 50%"}
                .col-sm-4.text-right
                  = f.submit "Save Changes", class: "btn btn-success"
                  = link_to wizard_property_address_path, class: "btn btn-default" do
                    Continue
            %section.scrollable.wrapper.w-f
              .panel-body
                .add-page
                  .row
                    .col-md-8.col-md-offset-2
                      = f.hidden_field :site_id, value: current_site_id
                      .line.line-dashed.b-b.line-lg.pull-in
                      .form-group
                        = f.label :title, "Page Title"
                        = f.text_field :title, class: "form-control"
                        %p Your page's main heading
                      .line.line-dashed.b-b.line-lg.pull-in
                      .form-group
                        = f.label :subtitle, "Page Subtitle"
                        = f.text_field :subtitle, class: "form-control"
                        %p Your page's sub heading
                      .line.line-dashed.b-b.line-lg.pull-in
                      .form-group
                        = f.label :content, "Page Content"
                        = f.text_area :content, id: "some-textarea", class: "wysihtml5 form-control"

app/views/wizards/property_amenities.html.haml
%body
  %section
    = form_for(@propertyinformations, html: { class: "propertyinformations-wizard" }) do |f|
      %section.hbox.stretch.wizard
        %aside
          %section.vbox
            %header.header.bg-white.b-b.clearfix
              .row
                .col-sm-4
                  = link_to wizard_property_address_path, class: "btn btn-default" do
                    Back
                .col-sm-4
                  - if Rails.env.development?
                    50% complete
                    .progress.progress-xs.m-t-sm{:style => "margin:0"}
                      .progress-bar.bg-info{"data-original-title" => "50%", "data-toggle" => "tooltip", :style => "width: 50%"}
                .col-sm-4.text-right
                  = f.submit "Save Changes", class: "btn btn-success"
                  = link_to wizard_templates_path, class: "btn btn-default" do
                    Continue
            %section.scrollable.wrapper.w-f
              .panel-body
                .add-page
                  .row
                    .col-md-8.col-md-offset-2
                      .top-info
                        %h1 Add Property Amenities
                        %p One more step before we can start editing your site! Let's save your property's amenities.
                      %h3{:style => "margin-bottom:30px;"} Amenities
                      .row
                        .col-md-2
                          %h4{:style => "margin:0;"} Common
                        .col-md-6
                          - @amenities_common.each do |amenity|
                            .form-group
                              .checkbox.m-n.i-checks
                                %label
                                  = f.check_box amenity.name
                                  %i
                                  = f.label amenity.name
                            / end form group
                      .row.m-t.m-b
                        .col-md-2
                          %h4{:style => "margin:0;"} Extra
                        .col-md-6
                          - @amenities_extra.each do |amenity|
                            .form-group
                              .checkbox.m-n.i-checks
                                %label
                                  = f.check_box amenity.name
                                  %i
                                  = f.label amenity.name
                            / end form group

app/views/wizards/templates.html.haml
%body
  %section.wizard
    %header.header.bg-white.b-b.clearfix
      .row
        .col-sm-4
          = link_to wizard_property_amenities_path, class: "btn btn-default" do
            Back
        .col-sm-4
          - if Rails.env.development?
            50% complete
            .progress.progress-xs{:style => "margin:0"}
              .progress-bar.bg-info{"data-original-title" => "50%", "data-toggle" => "tooltip", :style => "width: 50%"}
        .col-sm-4.text-right
          = link_to wizard_customize_path, class: "btn btn-default btn" do
            Continue
    %section.hbox.stretch
      %aside
        %section.vbox
          %div{:style => "position:absolute; height:100%; width:100%;"}
            - if Rails.env.production?
              %iframe{:src => "http://#{request.subdomain}.leasify.co"}
            - elsif Rails.env.development?
              %iframe{:src => "http://#{request.subdomain}.lvh.me:3000"}
      %aside#wizard_right_aside.b-l.aside-md
        %section.vbox
          %section.scrollable
            %h4{:style => "padding:20px 0 10px 16px;"} Choose Template
            - @templates.each do |template|
              = form_for(@themeoptions) do |f|
                .col-lg-12
                  .template-widget
                    = image_tag(template.theme_name_image.url(:large), id: "uploadimage", class: "img-responsive")
                    .template-widget-content
                      %h3= template.name
                      .row-fluid
                        = f.submit is_active_template(template) + " Template", class: "btn btn-s-md btn-" + active_template(template) + ""
                      = f.hidden_field :template, value: template.id
                      .row{:style => "margin-top:15px;"}
                        = link_to "http://" + template.name + "-demo.leasify.co", class: "link text-muted", target: "_blank" do
                          %em Live Example
  #template_tooltip.fake_tooltip.template
    %span.arrow.right
    Now the fun part begins!
    %br/
    Let's preview a template by clicking the
    "Activate Template" button. Click "Continue" once you've decided on a
    template.