config/routes.rb
Leasify::Application.routes.draw do

  require 'subdomain'

  resources :pages do
    collection do
      post "sort"
    end
  end

  resources :availabilities do
    collection do
      post "sort"
    end
  end

  resources :contacts do
    collection do
      post "sort"
    end
  end

  scope :dashboard do
    resources :pages, :availabilities, :contacts, :property_informations, :theme_options, :sites, :users, :homepage_galleries, :wizards
    get '/', to: 'dashboards#index', as: :dashboard
    get '/property',         to:'property_informations#index', as: :property
    get '/property/address', to:'property_informations#address', as: :address
    get '/property/amenities', to:'property_informations#amenities', as: :amenities_property
    get '/theme-options/logo', to:'theme_options#index', as: :logo
    get '/theme-options/homepage/content', to:'theme_options#homepage_content', as: :homepage_content
    get '/theme-options/homepage/gallery', to:'theme_options#homepage_gallery', as: :homepage_image_gallery
    get '/templates', to:'theme_options#template', as: :template
    get '/theme-options/settings', to:'theme_options#theme_settings', as: :theme_settings
    get '/tour', to:'dashboards#tour', as: :tour
    get '/redirect', to:'sites#redirect', as: :redirect

    # Wizard routes
    get '/wizard/templates', to: 'wizards#templates', as: :wizard_templates
    get '/wizard/customize', to: 'wizards#customize', as: :wizard_customize
    get '/wizard/homepage', to: 'wizards#homepage_content', as: :wizard_homepage_content
    get '/wizard/property', to: 'wizards#property_information', as: :wizard_property_information
    get '/wizard/property/address', to: 'wizards#property_address', as: :wizard_property_address
    get '/wizard/property/amenities', to: 'wizards#property_amenities', as: :wizard_property_amenities
    get '/wizard/homepage/gallery', to: 'wizards#homepage_gallery', as: :wizard_homepage_gallery
    get '/wizard/page/new', to: 'wizards#new_page', as: :wizard_new_page
    get '/wizard/almost/finished', to: 'wizards#almost_finished', as: :wizard_almost_finished
  end



  scope :admin do
    resources :theme_names, :sidebar_links, :admin, :amenities
    get '/themes', to: 'theme_names#index', as: :admin_theme
    get '/themes/new', to: 'theme_names#new', as: :admin_theme_new
    get '/themes/:id/edit', to: 'theme_names#edit', as: :admin_theme_edit
    get '/themes/:id/', to: 'theme_names#show', as: :admin_theme_show

    get '/sidebar/nav', to: 'sidebar_links#index', as: :admin_sidebar
    get '/sidebar/nav/new', to: 'sidebar_links#new', as: :admin_sidebar_new
    get '/sidebar/nav/:id/edit', to: 'sidebar_links#edit', as: :admin_sidebar_edit
    get '/sidebar/nav/:id', to: 'sidebar_links#show', as: :admin_sidebar_show

    get '/users', to: 'admin#users_list', as: :users_list

    get '/amenities', to: 'amenities#index', as: :admin_amenities
    get '/amenities/new', to: 'amenities#new', as: :admin_amenities_new
    get '/amenities/:id/edit', to: 'amenities#edit', as: :admin_amenities_edit
    get '/amenities/:id', to: 'amenities#show', as: :admin_amenities_show

    get '/slider', to: 'admin#slider_test'
  end

  constraints(Subdomains) do
    get '/' => 'static_pages#home'
  end

  root to: "static_pages#home"
  get '/help', to: 'static_pages#help', as: :help
  get '/templates', to: 'static_pages#templates', as: :templates
  get '/beta/signup', to: 'static_pages#beta_signup', as: :beta_signup_mailchimp
  get '/beta/confirmation', to: 'static_pages#beta_confirmation', as: :beta_confirmation_mailchimp
  get '/leasing', to: 'static_pages#leasing', as: :leasing
  get '/leasing/:id', to: 'availabilities#show', as: :leasing_show

  get "sunnyside/index"
  get "avaya/index"










  resources :users, :only => :show

  devise_for :users, :controllers => { :registrations => "registrations" },
             :skip => [:sessions, :passwords]

  devise_scope :user do
    get  '/register', to: 'devise/registrations#new', as: :register
    # post '/register', to: 'devise/registrations#create', as: :user_registration
    # put  '/register', to: 'devise/registrations#edit', as: :registration
    get  '/dashboard/profile/edit', to: 'devise/registrations#edit', as: :edit

    get  '/login', to: 'devise/sessions#new', as: :new_user_session
    post '/login', to: 'devise/sessions#create', as: :user_session
    get  '/logout', to: 'devise/sessions#destroy', as: :logout

    get  '/password/new', to: 'devise/passwords#new', as: :new_user_password
    post '/password/new', to: 'devise/passwords#create', as: :user_password
  end

  get '/:id', to: 'pages#show', as: 'pages_id'

  #post '/email_processor' => 'griddler/emails#create'

end

app/views/layouts/livingston/_footer.html.haml
%footer
  .container
    .row
      .col-md-12.center
        %p= @propertyinformation.name
        %p{:style => "margin-bottom:50px;"}
          = @propertyinformation.address
          , #{@propertyinformation.city},
          \#{@propertyinformation.state}, #{@propertyinformation.zipcode}
        %p
          Copyright © 2014
          \#{@propertyinformation.owner_name} / Powered by
          %a.customize-link{:href => "http://demo.leasify.co", :target => "_target"}
            Leasify

app/views/layouts/livingston/_head.html.haml
!!!
%html
  %head
    %meta{:content => "text/html; charset=UTF-8", "http-equiv" => "Content-Type"}/
    %title= @propertyinformation.name
    = stylesheet_link_tag "bootstrap.css", "bootstrap-wysihtml5.css", "livingston.css", "leasing.css", "font-awesome.min"
    = javascript_include_tag "jquery", "bootstrap", "app", "jquery.slimscroll.min", "app.plugin"
    = csrf_meta_tags
    - if Rails.env.production?
      / For leasify.co
      %script{:src => "//use.typekit.net/ckw2lgb.js", :type => "text/javascript"}
      :javascript
        try{Typekit.load();}catch(e){}
    - elsif Rails.env.development?
      / for lvh.me, remove when pushing to git and heroku
      %script{:src => "//use.typekit.net/bgg6ayr.js", :type => "text/javascript"}
      :javascript
        try{Typekit.load();}catch(e){}
    :css
      header ul li a {
      <haml_silent>       if @themeoptions.nav_color == &quot;#fff&quot; || @themeoptions.nav_color == &quot;#ffffff&quot; 
      </haml_silent><haml_block>      color: #000;
      </haml_block><haml_silent>       else 
      </haml_silent><haml_block>      color: #{@themeoptions.nav_color};
      </haml_block>      font-size: #{@themeoptions.nav_size.to_s}px;
          }
          header ul li a:hover {
            color: #{@themeoptions.navhover_color} !important;
          }
          footer p {
      <haml_silent>       if @themeoptions.footer_color == &quot;#fff&quot; || @themeoptions.footer_color == &quot;#ffffff&quot; 
      </haml_silent><haml_block>      color: #000;
      </haml_block><haml_silent>       else 
      </haml_silent><haml_block>      color: #{@themeoptions.footer_color};
      </haml_block>      font-size: #{@themeoptions.footer_size}px;
          }
          a.customize-link,
          .page-content a {
            color: #{@themeoptions.link_color};
          }
          
          .page-content p,
          .page-content {
      <haml_silent>       if @themeoptions.body_color == &quot;#fff&quot; || @themeoptions.body_color == &quot;#ffffff&quot; 
      </haml_silent><haml_block>      color: #000;
      </haml_block><haml_silent>       else 
      </haml_silent><haml_block>      color: #{@themeoptions.body_color};
      </haml_block>      font-size: #{@themeoptions.body_size}px;
          }
          .subpage-customize h1{
      <haml_silent>       if @themeoptions.page_title_color == &quot;#fff&quot; || @themeoptions.page_title_color == &quot;#ffffff&quot; 
      </haml_silent><haml_block>      color: #000;
      </haml_block><haml_silent>       else 
      </haml_silent><haml_block>      color: #{@themeoptions.page_title_color};
      </haml_block>      font-size: #{@themeoptions.page_title_size}px;
          }
          .subpage-customize p{
      <haml_silent>       if @themeoptions.page_subtitle_color == &quot;#fff&quot; || @themeoptions.page_subtitle_color == &quot;#ffffff&quot; 
      </haml_silent><haml_block>      color: #000;
      </haml_block><haml_silent>       else 
      </haml_silent><haml_block>      color: #{@themeoptions.page_subtitle_color};
      </haml_block>      font-size: #{@themeoptions.page_subtitle_size}px;
          }
          .page-content h1,
          .page-content h2,
          .page-content h3,
          .page-content h4,
          .page-content h5,
          .page-content h6 {
      <haml_silent>       if @themeoptions.body_heading_color == &quot;#fff&quot; || @themeoptions.body_heading_color == &quot;#ffffff&quot; 
      </haml_silent><haml_block>      color: #000;
      </haml_block><haml_silent>       else 
      </haml_silent><haml_block>      color: #{@themeoptions.body_heading_color} ;
      </haml_block>    }
          h1, h2, h3, h4, h5, h6 {
            text-transform: #{@themeoptions.heading_text_transform}; 
             #{font_name_for_heading_css.html_safe}
          }
          .welcome-box h1 {
      <haml_silent>       if @themeoptions.mainheading_color == &quot;#fff&quot; || @themeoptions.mainheading_color == &quot;#ffffff&quot; 
      </haml_silent><haml_block>      color: #000;
      </haml_block><haml_silent>       else 
      </haml_silent><haml_block>      font-size: #{@themeoptions.mainheading_size}px;
            color: #{@themeoptions.mainheading_color};
      </haml_block>    }
          .welcome-box p {
      <haml_silent>       if @themeoptions.subheading_color == &quot;#fff&quot; || @themeoptions.subheading_color == &quot;#ffffff&quot; 
      </haml_silent><haml_block>      color: #000;
      </haml_block><haml_silent>       else 
      </haml_silent><haml_block>      color: #{@themeoptions.subheading_color};
      </haml_block>      font-size: #{@themeoptions.subheading_size}px;
          }
          body {
            #{font_name_for_body_css.html_safe}
          }
      
      <haml_silent>     if @themeoptions.nav_color == &quot;#fff&quot; 
      </haml_silent><haml_block>      header ul li a {
            color: #999;
            }
      </haml_block><haml_silent>     if @themeoptions.mainheading_color == &quot;#fff&quot; 
      </haml_silent><haml_block>      .welcome-box h1 {
              color: #000;
            }
      </haml_block><haml_silent>     if @themeoptions.subheading_color == &quot;#fff&quot; 
      </haml_silent><haml_block>      .welcome-box p {
              color: #000;
            }
      </haml_block>

app/views/layouts/livingston/_header.html.haml
= draft_page_error_alert
= draft_listing_error_alert
- if params[:action] == "show" && params[:controller] == "pages"
  %header#top.navbar.navbar-fixed-top{:role => "banner", :style => "#{'margin-top:50px;' if !@page.published?}"}
- elsif params[:action] == "show" && params[:controller] == "availabilities"
  %header#top.navbar.navbar-fixed-top{:role => "banner", :style => "#{'margin-top:50px;' if !@availability.published?}"}
- else
  %header#top.navbar.navbar-fixed-top{:role => "banner"}
.container-fluid
  .navbar-header
    %button.navbar-toggle{"data-target" => ".bs-navbar-collapse", "data-toggle" => "collapse", :type => "button"}
      %span.sr-only Toggle navigation
      %span.icon-bar
      %span.icon-bar
      %span.icon-bar
    = show_logo_sunnyside
  %nav.collapse.navbar-collapse.bs-navbar-collapse{:role => "navigation"}
    %ul.nav.navbar-nav.navbar-right
      - @page_root.each do |page|
        %li
          = link_to page.title, pages_id_path(page)
          - unless Page.where(site_id: @site.id, parent_id: page.id).empty?
            %ul
              - Page.where(site_id: @site.id, parent_id: page.id).each do |child|
                %li= link_to child.title, pages_id_path(child)
      - unless @availabilities.empty?
        %li= link_to "Leasing", leasing_path
      %li= admin_link